// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBVEvvi7MALQeN9JxoGbiujaD-fAcrM18',
    appId: '1:213607786934:web:7dbdfe9afc0b03d9b17917',
    messagingSenderId: '213607786934',
    projectId: 'mae-assignment-a1b2d',
    authDomain: 'mae-assignment-a1b2d.firebaseapp.com',
    databaseURL: 'https://mae-assignment-a1b2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-assignment-a1b2d.firebasestorage.app',
    measurementId: 'G-YG6HZGYX6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BRJVSOiPryVq1lcGd6avOSWbGWKBlfY',
    appId: '1:213607786934:android:f8975fb43917c79cb17917',
    messagingSenderId: '213607786934',
    projectId: 'mae-assignment-a1b2d',
    databaseURL: 'https://mae-assignment-a1b2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-assignment-a1b2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXTOlA5CZFovklopK6zMzEOw9ZgL-1Ew',
    appId: '1:213607786934:ios:adb077ff1f907f2eb17917',
    messagingSenderId: '213607786934',
    projectId: 'mae-assignment-a1b2d',
    databaseURL: 'https://mae-assignment-a1b2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-assignment-a1b2d.firebasestorage.app',
    iosBundleId: 'com.nabrental.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXTOlA5CZFovklopK6zMzEOw9ZgL-1Ew',
    appId: '1:213607786934:ios:dc13e0dd1f9fc277b17917',
    messagingSenderId: '213607786934',
    projectId: 'mae-assignment-a1b2d',
    storageBucket: 'mae-assignment-a1b2d.firebasestorage.app',
    iosBundleId: 'com.example.nab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBVEvvi7MALQeN9JxoGbiujaD-fAcrM18',
    appId: '1:213607786934:web:3e05a59f3d83a4c2b17917',
    messagingSenderId: '213607786934',
    projectId: 'mae-assignment-a1b2d',
    authDomain: 'mae-assignment-a1b2d.firebaseapp.com',
    storageBucket: 'mae-assignment-a1b2d.firebasestorage.app',
    measurementId: 'G-WL442P90QZ',
  );
}